print('Hello world!\nHello world!\nHello world!')
print('Hello'+' Murtaza')
print('Hello','Murtaza')
print('Hello'+' '+'Murtaza')
#  print("hello") #IndentationError if we keep space before print()
print('Day 1 - String Manipulation')
print('String Concatenation is done with '+'+'+' sign')
print('e.g. print("Hello "+"world")')
print("New lines are created by \\n")
